services:
  postgres:
    image: postgres:16-alpine
    container_name: dabro_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - dabro_net
    restart: unless-stopped

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - backend/.env.prod
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "8000"
    networks:
      - dabro_net
    restart: unless-stopped

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      NUXT_PUBLIC_API_BASE_URL: ${NUXT_API_BASE_URL}
      NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL}
    ports:
      - "3000:3000"
    networks:
      - dabro_net

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: dabro_nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - dabro_net
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: dabro_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  postgres_data:

networks:
  dabro_net:
    driver: bridge