"""init

Revision ID: 11127867287c
Revises: f019c6cf331b
Create Date: 2026-02-15 20:41:00.012616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11127867287c'
down_revision: Union[str, Sequence[str], None] = 'f019c6cf331b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('items_left', sa.Integer(), nullable=False))
    op.drop_column('product', 'booked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('booked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('product', 'items_left')
    # ### end Alembic commands ###
