"""staff img_id to img_url

Revision ID: 15236e6a7fd0
Revises: ae8cf2d56a26
Create Date: 2026-03-09 12:35:38.342252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15236e6a7fd0'
down_revision: Union[str, Sequence[str], None] = 'ae8cf2d56a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('img_url', sa.String(), nullable=True))
    op.drop_column('staff', 'img_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('img_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('staff', 'img_url')
    # ### end Alembic commands ###
