"""product_modal add title

Revision ID: 416dca3d5ed8
Revises: 49f060889b5c
Create Date: 2026-03-12 18:49:58.210216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '416dca3d5ed8'
down_revision: Union[str, Sequence[str], None] = '49f060889b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'title')
    # ### end Alembic commands ###
