"""img_id -> img_url_v2

Revision ID: 533de7c85c86
Revises: 2bd71ca237c7
Create Date: 2026-03-08 19:06:29.925506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533de7c85c86'
down_revision: Union[str, Sequence[str], None] = '2bd71ca237c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_img', sa.Text(), nullable=True))
    op.drop_column('product', 'img_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('product', 'img_img')
    # ### end Alembic commands ###
