"""init

Revision ID: a31273bacec1
Revises: ad751a2b9df6
Create Date: 2026-02-16 12:04:47.853262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31273bacec1'
down_revision: Union[str, Sequence[str], None] = 'ad751a2b9df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_id', sa.Text(), nullable=False))
    op.drop_column('product', 'img_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('product', 'img_id')
    # ### end Alembic commands ###
