"""img_id -> img_url_v3

Revision ID: ae8cf2d56a26
Revises: 533de7c85c86
Create Date: 2026-03-08 19:22:55.333451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8cf2d56a26'
down_revision: Union[str, Sequence[str], None] = '533de7c85c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_url', sa.Text(), nullable=True))
    op.drop_column('product', 'img_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_img', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('product', 'img_url')
    # ### end Alembic commands ###
