"""init

Revision ID: bd5b0010a1dd
Revises: a31273bacec1
Create Date: 2026-02-17 21:58:29.562995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5b0010a1dd'
down_revision: Union[str, Sequence[str], None] = 'a31273bacec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sa.String(length=30), nullable=False))
    op.add_column('product', sa.Column('category', sa.String(length=30), nullable=False))
    op.drop_column('product', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('product', 'category')
    op.drop_column('product', 'brand')
    # ### end Alembic commands ###
