"""init

Revision ID: de1fc59c3463
Revises: 458f23bf25e7
Create Date: 2026-03-02 20:00:56.890551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1fc59c3463'
down_revision: Union[str, Sequence[str], None] = '458f23bf25e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('excel_product_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'excel_product_id')
    # ### end Alembic commands ###
