"""updated product_modal

Revision ID: 49f060889b5c
Revises: 15236e6a7fd0
Create Date: 2026-03-12 18:46:09.387492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f060889b5c'
down_revision: Union[str, Sequence[str], None] = '15236e6a7fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'excel_product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'brand',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('product', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('product', 'size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('product', 'brand',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('product', 'excel_product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
