"""delite products

Revision ID: a9008401efb8
Revises: 416dca3d5ed8
Create Date: 2026-09-06 14:46:38.986634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9008401efb8'
down_revision: Union[str, Sequence[str], None] = '416dca3d5ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('items_left', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('excel_product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('img_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_id', name=op.f('product_pkey'))
    )
    # ### end Alembic commands ###
